/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mdsaz
 */
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;

public class AddFriendForm extends javax.swing.JFrame {

    private JTextField nameField;
    private JTextField emailField;

    /**
     * Creates new form AddFriendForm
     */
    public AddFriendForm() {

        setTitle("Add Friend");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        // Create form components
        JLabel nameLabel = new JLabel("Name:");
        JLabel emailLabel = new JLabel("Email:");
        nameField = new JTextField(20);
        emailField = new JTextField(20);
        JButton addButton = new JButton("Add");

        // Create panel and add components
        JPanel panel = new JPanel(new GridLayout(3, 2));
        panel.add(nameLabel);
        panel.add(nameField);
        panel.add(emailLabel);
        panel.add(emailField);
        panel.add(addButton);

        // Handle add button click
        addButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String name = nameField.getText();
                String email = emailField.getText();

                // Insert data into the database
                try {
                    Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/facebookaccount", "root", "");
                    String query = "INSERT INTO frnd (Name, Phone) VALUES (?, ?)";
                    PreparedStatement statement = connection.prepareStatement(query);
                    System.out.println("database connected ");

                    statement.setString(1, name);
                    statement.setString(2, email);
                    statement.executeUpdate();

                    if (name.isEmpty() || email.isEmpty()) {
                        JOptionPane.showMessageDialog(null, "Fill up the feild ");
                    } else {
                        JOptionPane.showMessageDialog(null, "Friend added successfully");
                        Mainmanu mn = new Mainmanu();
                        mn.setVisible(true);
                        connection.close();
                    }
                } catch (SQLException ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(null, ex);
                }
            }
        });

        // Set panel as the content pane
        setContentPane(panel);
        pack();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AddFriendForm();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
